#!/bin/sh
python - <<END
fn = 'locations.txt'
fout = 'new-locations.js'
f = open(fn)
lines = f.readlines()
f.close()
js = open(fout, 'w+')
js.write('/* THIS FILE IS AUTOMATICALLY GENERATED*/\n\n')
js.write('/* windgram location variable\n')
js.write('* [region, location] */\n\n')
js.write('var locations=new Array();\n')
for i in range(0, len(lines)-1):
    split_line = lines[i+1].split(',')
    if len(split_line) >= 2 :
        js.write('locations[' + str(i) + ']=["' + split_line[0].strip() + '","' + split_line[1].strip() + '",' + split_line[2].strip() + ',' + split_line[3].strip() + '];\n')
    else:
        print "error on line " + str(i) + " of " + fn + ". Found " + str(len(split_line)) + " fields. Expected 2 or more"
js.close()
print "Converted " + fn + " to a javascript format file, " + fout
END


