; RESOURCES FOR (SIMPLE) CONTOUR PLOTS

opts_cn                 = True
opts_cn@lbLabelBarOn    = False
opts_cn@cnFillOn        = True      ; color fill
opts_cn@cnLinesOn       = False     ; no contour lines
opts_cn@cnLineLabelsOn  = False     ; no contour labels
opts_cn@gsnSpreadColors = True      ; use total colormap
opts_cn@cnInfoLabelOn   = False     ; no contour info label
opts_cn@gsnDraw         = False
opts_cn@gsnFrame        = False
